# Generated by Django 5.2.3 on 2025-06-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_preferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say'), ('non_binary', 'Non-binary')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='intrested_in',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say'), ('non_binary', 'Non-binary')], max_length=100, null=True),
        ),
    ]
